services:

  otelcol:
    build:
      context: .
      dockerfile: otelcol.Dockerfile
    container_name: otelcol
  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports:
      - '8080:8080'
      - '8083:8083'
    command: [ "-m", "prometheus", "all" ]
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger-agent:5778/sampling
    depends_on:
      - jaeger-agent

  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: 
      - "--reporter.grpc.host-port=otelcol:14250"
      - "--agent.tags=custom.tag=00000000-0000-0000-0000-000000000000"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
